[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brainco-mjlab-tasks"
version = "0.1.0"
description = "BrainCo task package for mjlab."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [

]

[project.entry-points."mjlab.tasks"]
brainco_mjlab_tasks = "brainco_mjlab_tasks"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

